site_name: POSSIBLE

theme:
  name: material
  palette:
    primary: blue
    scheme: slate
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.indexes 
  icon:
    logo: fontawesome/solid/x

copyright: Copyright &copy; 2023 POSSIBLE Project

extra:
  social:
    - icon: fontawesome/solid/house
      link: https://www.possible-gaia-x.eu/
    - icon: fontawesome/brands/github
      link: https://github.com/POSSIBLE-X


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Architecture:
    - architecture/index.md
  - Access Control:
    - access-control/index.md
  - Catalog:
    - catalog/index.md
    - Self Descriptions: catalog/self-descriptions.md
  - Connector:
    - connector/index.md