openapi: 3.0.1
paths:
  /v2/contractnegotiations:
    post:
      description: "Initiates a contract negotiation for a given offer and with the\
        \ given counter part. Please note that successfully invoking this endpoint\
        \ only means that the negotiation was initiated. Clients must poll the /{id}/state\
        \ endpoint to track the state"
      operationId: initiateContractNegotiation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NegotiationInitiateRequestDto'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdResponseDto'
          description: The negotiation was successfully initiated. Returns the contract
            negotiation ID and created timestamp
          links:
            poll-state:
              operationId: getNegotiationState
              parameters:
                id: $response.body#/id
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: Request body was malformed
      tags:
      - Contract Negotiation
  /v2/contractnegotiations/request:
    post:
      description: Returns all contract negotiations according to a query
      operationId: queryNegotiations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuerySpecDto'
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ContractNegotiationDto'
          description: The contract negotiations that match the query
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: Request was malformed
      tags:
      - Contract Negotiation
  /v2/contractnegotiations/{id}:
    get:
      description: Gets a contract negotiation with the given ID
      operationId: getNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractNegotiationDto'
          description: The contract negotiation
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: An contract negotiation with the given ID does not exist
      tags:
      - Contract Negotiation
  /v2/contractnegotiations/{id}/agreement:
    get:
      description: Gets a contract agreement for a contract negotiation with the given
        ID
      operationId: getAgreementForNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractAgreementDto'
          description: "The contract agreement that is attached to the negotiation,\
            \ or null"
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: An contract negotiation with the given ID does not exist
      tags:
      - Contract Negotiation
  /v2/contractnegotiations/{id}/cancel:
    post:
      description: "Requests aborting the contract negotiation. Due to the asynchronous\
        \ nature of contract negotiations, a successful response only indicates that\
        \ the request was successfully received. Clients must poll the /{id}/state\
        \ endpoint to track the state."
      operationId: cancelNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      responses:
        "200":
          description: Request to cancel the Contract negotiation was successfully
            received
          links:
            poll-state:
              operationId: getNegotiationState
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: A contract negotiation with the given ID does not exist
      tags:
      - Contract Negotiation
  /v2/contractnegotiations/{id}/decline:
    post:
      description: "Requests cancelling the contract negotiation. Due to the asynchronous\
        \ nature of contract negotiations, a successful response only indicates that\
        \ the request was successfully received. Clients must poll the /{id}/state\
        \ endpoint to track the state."
      operationId: declineNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      responses:
        "200":
          description: Request to decline the Contract negotiation was successfully
            received
          links:
            poll-state:
              operationId: getNegotiationState
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: A contract negotiation with the given ID does not exist
      tags:
      - Contract Negotiation
  /v2/contractnegotiations/{id}/state:
    get:
      description: Gets the state of a contract negotiation with the given ID
      operationId: getNegotiationState
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NegotiationState'
          description: The contract negotiation's state
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: An contract negotiation with the given ID does not exist
      tags:
      - Contract Negotiation
components:
  schemas:
    Action:
      type: object
      example: null
      properties:
        constraint:
          $ref: '#/components/schemas/Constraint'
        includedIn:
          type: string
          example: null
        type:
          type: string
          example: null
    ApiErrorDetail:
      type: object
      example: null
      properties:
        invalidValue:
          type: string
          example: null
        message:
          type: string
          example: null
        path:
          type: string
          example: null
        type:
          type: string
          example: null
    CallbackAddress:
      type: object
      example: null
      properties:
        authCodeId:
          type: string
          example: null
        authKey:
          type: string
          example: null
        events:
          type: array
          example: null
          items:
            type: string
            example: null
          uniqueItems: true
        transactional:
          type: boolean
          example: null
        uri:
          type: string
          example: null
    Constraint:
      type: object
      discriminator:
        propertyName: edctype
      example: null
      properties:
        edctype:
          type: string
          example: null
      required:
      - edctype
    ContractAgreementDto:
      type: object
      example: null
      properties:
        assetId:
          type: string
          example: null
        consumerId:
          type: string
          example: null
        contractSigningDate:
          type: integer
          format: int64
          example: null
        id:
          type: string
          example: null
        policy:
          $ref: '#/components/schemas/Policy'
        providerId:
          type: string
          example: null
      required:
      - assetId
      - consumerId
      - id
      - policy
      - providerId
    ContractNegotiationDto:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@id':
          type: string
          example: null
        '@type':
          type: string
          example: null
        callbackAddresses:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/CallbackAddress'
        contractAgreementId:
          type: string
          example: null
        counterPartyAddress:
          type: string
          example: null
        createdAt:
          type: integer
          format: int64
          example: null
        errorDetail:
          type: string
          example: null
        protocol:
          type: string
          example: null
        state:
          type: string
          example: null
        type:
          type: string
          enum:
          - CONSUMER
          - PROVIDER
          example: null
        updatedAt:
          type: integer
          format: int64
          example: null
    ContractOfferDescription:
      type: object
      example: null
      properties:
        assetId:
          type: string
          example: null
        offerId:
          type: string
          example: null
        policy:
          $ref: '#/components/schemas/Policy'
    CriterionDto:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@type':
          type: string
          example: null
        operandLeft:
          type: object
          example: null
        operandRight:
          type: object
          example: null
        operator:
          type: string
          example: null
      required:
      - operandLeft
      - operator
    Duty:
      type: object
      example: null
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        consequence:
          $ref: '#/components/schemas/Duty'
        constraints:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Constraint'
        parentPermission:
          $ref: '#/components/schemas/Permission'
        target:
          type: string
          example: null
    IdResponseDto:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@id':
          type: string
          example: null
        '@type':
          type: string
          example: null
        createdAt:
          type: integer
          format: int64
          example: null
    JsonArray:
      type: array
      example: null
      items:
        $ref: '#/components/schemas/JsonValue'
      properties:
        empty:
          type: boolean
          example: null
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
          example: null
    JsonObject:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/JsonValue'
      example: null
      properties:
        empty:
          type: boolean
          example: null
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
          example: null
    JsonValue:
      type: object
      example: null
      properties:
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
          example: null
    NegotiationInitiateRequestDto:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@type':
          type: string
          example: null
        callbackAddresses:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/CallbackAddress'
        connectorAddress:
          type: string
          example: null
        connectorId:
          type: string
          example: null
        consumerId:
          type: string
          example: null
        offer:
          $ref: '#/components/schemas/ContractOfferDescription'
        protocol:
          type: string
          example: null
        providerId:
          type: string
          example: null
    NegotiationState:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@type':
          type: string
          example: null
        state:
          type: string
          example: null
    Permission:
      type: object
      example: null
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        constraints:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Constraint'
        duties:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Duty'
        target:
          type: string
          example: null
    Policy:
      type: object
      example: null
      properties:
        '@type':
          type: string
          enum:
          - SET
          - OFFER
          - CONTRACT
          example: null
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        extensibleProperties:
          type: object
          additionalProperties:
            type: object
            example: null
          example: null
        inheritsFrom:
          type: string
          example: null
        obligations:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Duty'
        permissions:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Permission'
        prohibitions:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Prohibition'
        target:
          type: string
          example: null
    Prohibition:
      type: object
      example: null
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        constraints:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Constraint'
        target:
          type: string
          example: null
    QuerySpecDto:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@type':
          type: string
          example: null
        filterExpression:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/CriterionDto'
        limit:
          type: integer
          format: int32
          example: null
        offset:
          type: integer
          format: int32
          example: null
        sortField:
          type: string
          example: null
        sortOrder:
          type: string
          enum:
          - ASC
          - DESC
          example: null
