openapi: 3.0.1
paths:
  /v2/transferprocesses:
    post:
      description: "Initiates a data transfer with the given parameters. Please note\
        \ that successfully invoking this endpoint only means that the transfer was\
        \ initiated. Clients must poll the /{id}/state endpoint to track the state"
      operationId: initiateTransferProcess
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequestDto'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdResponseDto'
          description: The transfer was successfully initiated. Returns the transfer
            process ID and created timestamp
          links:
            poll-state:
              operationId: getTransferProcessState
              parameters:
                id: $response.body#/id
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: Request body was malformed
      tags:
      - Transfer Process
  /v2/transferprocesses/request:
    post:
      description: Returns all transfer process according to a query
      operationId: queryTransferProcesses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuerySpecDto'
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/TransferProcessDto'
          description: The transfer processes matching the query
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: Request was malformed
      tags:
      - Transfer Process
  /v2/transferprocesses/{id}:
    get:
      description: Gets an transfer process with the given ID
      operationId: getTransferProcess
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferProcessDto'
          description: The transfer process
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: A transfer process with the given ID does not exist
      tags:
      - Transfer Process
  /v2/transferprocesses/{id}/deprovision:
    post:
      description: "Requests the deprovisioning of resources associated with a transfer\
        \ process. Due to the asynchronous nature of transfers, a successful response\
        \ only indicates that the request was successfully received. This may take\
        \ a long time, so clients must poll the /{id}/state endpoint to track the\
        \ state."
      operationId: deprovisionTransferProcess
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      responses:
        "200":
          description: Request to deprovision the transfer process was successfully
            received
          links:
            poll-state:
              operationId: getTransferProcessState
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: A contract negotiation with the given ID does not exist
      tags:
      - Transfer Process
  /v2/transferprocesses/{id}/state:
    get:
      description: Gets the state of a transfer process with the given ID
      operationId: getTransferProcessState
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferState'
          description: The  transfer process's state
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: An  transfer process with the given ID does not exist
      tags:
      - Transfer Process
  /v2/transferprocesses/{id}/terminate:
    post:
      description: "Requests the termination of a transfer process. Due to the asynchronous\
        \ nature of transfers, a successful response only indicates that the request\
        \ was successfully received. Clients must poll the /{id}/state endpoint to\
        \ track the state."
      operationId: terminateTransferProcess
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TerminateTransferDto'
      responses:
        "200":
          description: Request to cancel the transfer process was successfully received
          links:
            poll-state:
              operationId: getTransferProcessState
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: A contract negotiation with the given ID does not exist
        "409":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Could not terminate transfer process, because it is already\
            \ completed or terminated."
      tags:
      - Transfer Process
components:
  schemas:
    ApiErrorDetail:
      type: object
      example: null
      properties:
        invalidValue:
          type: string
          example: null
        message:
          type: string
          example: null
        path:
          type: string
          example: null
        type:
          type: string
          example: null
    CallbackAddress:
      type: object
      example: null
      properties:
        authCodeId:
          type: string
          example: null
        authKey:
          type: string
          example: null
        events:
          type: array
          example: null
          items:
            type: string
            example: null
          uniqueItems: true
        transactional:
          type: boolean
          example: null
        uri:
          type: string
          example: null
    CriterionDto:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@type':
          type: string
          example: null
        operandLeft:
          type: object
          example: null
        operandRight:
          type: object
          example: null
        operator:
          type: string
          example: null
      required:
      - operandLeft
      - operator
    DataAddress:
      type: object
      example: null
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
            example: null
          example: null
    DataAddressDto:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@type':
          type: string
          example: null
        properties:
          type: object
          additionalProperties:
            type: string
            example: null
          example: null
      required:
      - properties
    DataRequestDto:
      type: object
      example: null
      properties:
        assetId:
          type: string
          example: null
        connectorId:
          type: string
          example: null
        contractId:
          type: string
          example: null
        id:
          type: string
          example: null
    IdResponseDto:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@id':
          type: string
          example: null
        '@type':
          type: string
          example: null
        createdAt:
          type: integer
          format: int64
          example: null
    JsonArray:
      type: array
      example: null
      items:
        $ref: '#/components/schemas/JsonValue'
      properties:
        empty:
          type: boolean
          example: null
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
          example: null
    JsonObject:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/JsonValue'
      example: null
      properties:
        empty:
          type: boolean
          example: null
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
          example: null
    JsonValue:
      type: object
      example: null
      properties:
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
          example: null
    QuerySpecDto:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@type':
          type: string
          example: null
        filterExpression:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/CriterionDto'
        limit:
          type: integer
          format: int32
          example: null
        offset:
          type: integer
          format: int32
          example: null
        sortField:
          type: string
          example: null
        sortOrder:
          type: string
          enum:
          - ASC
          - DESC
          example: null
    TerminateTransferDto:
      type: object
      example: null
      properties:
        reason:
          type: string
          example: null
      required:
      - reason
    TransferProcessDto:
      type: object
      example: null
      properties:
        '@context':
          type: object
          example: null
        '@id':
          type: string
          example: null
        '@type':
          type: string
          example: null
        callbackAddresses:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/CallbackAddress'
        createdAt:
          type: integer
          format: int64
          example: null
        dataDestination:
          $ref: '#/components/schemas/DataAddressDto'
        dataRequest:
          $ref: '#/components/schemas/DataRequestDto'
        errorDetail:
          type: string
          example: null
        properties:
          type: object
          additionalProperties:
            type: string
            example: null
          example: null
        state:
          type: string
          example: null
        stateTimestamp:
          type: integer
          format: int64
          example: null
        type:
          type: string
          example: null
        updatedAt:
          type: integer
          format: int64
          example: null
    TransferRequestDto:
      type: object
      example: null
      properties:
        assetId:
          type: string
          example: null
        callbackAddresses:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/CallbackAddress'
        connectorAddress:
          type: string
          example: null
        connectorId:
          type: string
          example: null
        contractId:
          type: string
          example: null
        dataDestination:
          $ref: '#/components/schemas/DataAddress'
        id:
          type: string
          example: null
        managedResources:
          type: boolean
          example: null
        privateProperties:
          type: object
          additionalProperties:
            type: string
            example: null
          example: null
        properties:
          type: object
          additionalProperties:
            type: string
            example: null
          example: null
        protocol:
          type: string
          example: null
      required:
      - assetId
      - connectorAddress
      - connectorId
      - contractId
      - dataDestination
      - protocol
    TransferState:
      type: object
      example: null
      properties:
        state:
          type: string
          example: null
